upgrade lifecycle handler
neume-network/strategies pull request #168
Opened 2022-07-11 10:58 UTC by il3ven

This is a proposal for an upgrade in lifecycle handler. It solves two main problems.
- We now know when an extractor has completed and we can then call it's transformer. This should solve problems like #154.
- We now also know when a strategy has ended. This should solve problems like #146.

Additional benefit:
- We can now define a [path](https://github.com/neume-network/strategies/blob/2bff5f4fda838239de8426806d330eee79c85916/src/lifecycle.mjs#L202) for the crawler to take in advance.

@TimDaub Have a look at the implementation. I tested it with minimal data and it works. I couldn't test it completely because of no IPFS gateway access right now. I'll try to test more and iron out the bugs.

2022-07-11 11:54 UTC, TimDaub commented
@reimertz can we set up @il3ven with an IPFS gateway access?

2022-07-11 11:55 UTC, TimDaub commented on src/lifecycle.mjs
> +  const graph = [
this is amazing, I wanted to have something like this since a while!

2022-07-11 14:34 UTC, TimDaub commented
this may also resolve: https://github.com/neume-network/strategies/issues/170

2022-07-11 14:51 UTC, TimDaub requested changes
hard requirement is that all new functionality must be unit tested

2022-07-11 14:53 UTC, TimDaub commented
> hard requirement is that all new functionality must be unit tested

Added issue for this too: https://github.com/neume-network/strategies/issues/174

2022-07-11 15:07 UTC, TimDaub commented
- It's not a blocker for this PR but eventually we want to specify the graph as a json schema: https://github.com/neume-network/message-schema/issues/19

2022-07-13 12:19 UTC, il3ven commented
I ran a small crawl using this PR. It ran successfully. I crawled 543 NFTs. The strategy was to limit the NFTs in web3subgraph-transformation. The crawl took 3m40s with a concurrency of 50. For IPFS I used `ipfs.io/ipfs` as my gateway.

Here is the crawl data if you are interested. [data.zip](https://github.com/neume-network/strategies/files/9101993/data.zip)

I think only unit tests are remaining to be added.

2022-07-16 10:03 UTC, il3ven commented
Due to lack of reviewer, merging this branch to dev for now. So I can run the crawler without affecting master.

2022-07-16 10:04 UTC, merged